blog/urls.py
from django.urls import path
from django.conf import settings #For Media
from django.conf.urls.static import static #For Media
from .views import BlogListView, BlogDetailView



app_name = 'blog'


urlpatterns = [
	path('all/', BlogListView.as_view(), name='all-blogs'),
	path('<slug:blog_slug>/', BlogDetailView.as_view(), name='blog-detail'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketing/urls.py
from django.urls import path
from .views import TestimonialListView


app_name = 'marketing'


urlpatterns = [
	path('testimonials/', TestimonialListView.as_view(), name='all-testimonials'),
]

page/urls.py
from django.urls import path
from django.conf import settings #Needed for MEdia
from django.conf.urls.static import static # For MEdia
from .views import HomePageView, BlogPageView, ContactPageView, PageDetailView



app_name = 'page'


urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('blog/', BlogPageView.as_view(), name='blog'),
    path('contact/', ContactPageView.as_view(), name='contact'),
    path('<slug:page_slug>/', PageDetailView.as_view(), name='page-detail'),

    

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tour/urls.py
from django.urls import path
from django.conf import settings #Needed for MEdia
from django.conf.urls.static import static # For MEdia
from .views import ActivityListView, RegionListView, TourListView, TourDetailView, RegionDetailView, ActivityDetailView



app_name = 'tour'


urlpatterns = [
	path('all/', TourListView.as_view(), name='all-tours'),
	path('activities/', ActivityListView.as_view(), name='all-activities'),
	path('activity/<slug:activity_slug>/', ActivityDetailView.as_view(), name='activity-detail'),
	path('regions/', RegionListView.as_view(), name='all-regions'),
	path('region/<slug:region_slug>/', RegionDetailView.as_view(), name='region-detail'),
	path('<slug:tour_slug>/', TourDetailView.as_view(), name='tour-detail'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

travel_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('page.urls')),
    path('tour/', include('tour.urls')),
    path('blog/', include('blog.urls')),
    path('marketing/', include('marketing.urls')),
]


# Customizing Admin Panel Texts
admin.site.site_header = 'Django Travel Project'
admin.site.index_title = 'Manage Travels'
admin.site.site_title = 'Travel Site | Control Panel'

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

# Create your models here.
IS_ACTIVE = (
		('yes', 'Yes'),
		('no', 'No')
	)




class Category(models.Model):
	category_title = models.CharField(max_length=200, verbose_name='Category Title')
	category_slug = models.SlugField(max_length=200, verbose_name='Category Slug')
	category_description = models.TextField(blank=True, null=True, verbose_name='Category Description')
	category_image = models.ImageField(upload_to='categories/', blank=True, null=True)
	category_is_active = models.CharField(
			choices = IS_ACTIVE,
			default = 'Yes',
			max_length = 10,
			verbose_name = 'Is Active?'
		)
	category_created_at = models.DateTimeField(auto_now_add=True, verbose_name='Category Created Date')
	category_updated_at = models.DateTimeField(auto_now=True, verbose_name='Category Updated Date')
	category_added_by = models.ForeignKey(User, on_delete=models.SET_NULL, default=None, null=True, verbose_name='Added By')

	# Meta for SEO
	seo_category_title = models.CharField(max_length=200, blank=True, null=True, verbose_name='SEO Category Title (60 Characters Long)')
	seo_category_keywords = models.TextField(blank=True, null=True, verbose_name='SEO Category Keywords Separated by Commas')
	seo_category_description = models.TextField(blank=True, null=True, verbose_name='SEO Category Description (160 Characters Long)')


	def __str__(self):
		return self.category_title




class Blog(models.Model):
	blog_title = models.CharField(max_length=200, verbose_name='Blog Title')
	blog_slug = models.CharField(max_length=200, verbose_name='Blog Slug')
	blog_description = RichTextField(blank=True, null=True, verbose_name='Blog Description')
	blog_image = models.ImageField(upload_to='blogs/', blank=True, null=True, verbose_name='Blog Image')
	blog_category = models.ManyToManyField(Category, verbose_name='Blog Category')
	blog_is_active = models.CharField(
			choices = IS_ACTIVE,
			default = 'Yes',
			max_length = 10,
			verbose_name = 'Is Active?'
		)
	blog_is_featured = models.CharField(
			choices = IS_ACTIVE,
			default = 'Yes',
			max_length = 10,
			verbose_name = 'Is Featured?'
		)
	blog_created_at = models.DateTimeField(auto_now_add=True, verbose_name='Blog Created Date')
	blog_updated_at = models.DateTimeField(auto_now=True, verbose_name='Blog Updated Date')
	blog_added_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name='Added By')


	# Meta for SEO
	seo_blog_title = models.CharField(max_length=200, blank=True, null=True, verbose_name='SEO Blog Title (60 Characters Long)')
	seo_blog_keywords = models.TextField(blank=True, null=True, verbose_name='SEO Blog Keywords (Separated by Commas)')
	seo_blog_description = models.TextField(blank=True, null=True, verbose_name='SEO Blog Description (160 Characters Long)')


	def __str__(self):
		return self.blog_title


	class Meta:
		ordering = ['-blog_created_at']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View, TemplateView, DetailView, ListView
from .models import Blog

# Create your views here.


class BlogListView(ListView):
	template_name = 'blog/all_blogs.html'
	model = Blog
	context_object_name = 'blogs'
	paginate_by = 6



class BlogDetailView(DetailView):
	template_name = 'blog/blog_detail.html'
	model = Blog
	slug_url_kwarg = 'blog_slug'
	slug_field = 'blog_slug'
	context_object_name = 'blog'


	def get_context_data(self, **kwargs):
		current_blog = get_object_or_404(Blog, blog_slug=self.kwargs.get('blog_slug'))
		similar_blogs = Blog.objects.filter(blog_is_active='yes', blog_category__in=current_blog.blog_category.all()).exclude(blog_slug=self.kwargs.get('blog_slug')).order_by('-blog_created_at')[:3]
		other_blogs = Blog.objects.filter(blog_is_active='yes').order_by('-blog_created_at')[:3]

		context = super().get_context_data(**kwargs)
		context['similar_blogs'] = similar_blogs
		context['other_blogs'] = other_blogs
		return context

templates/base.html
{% load static %}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="author" content="{{ this_app.developed_by }}" />
	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="{{ this_app.app_icon.url }}">

	{% block meta_content %}
	{% endblock meta_content %}

	<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>
	
	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<!-- Superfish -->
	<link rel="stylesheet" href="{% static 'css/superfish.css' %}">
	<!-- Magnific Popup -->
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
	<!-- Date Picker -->
	<link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.min.css' %}">
	<!-- CS Select -->
	<link rel="stylesheet" href="{% static 'css/cs-select.css' %}">
	<link rel="stylesheet" href="{% static 'css/cs-skin-border.css' %}">
	
	<link rel="stylesheet" href="{% static 'css/style.css' %}">

	<style>
		.img-logo{
			height: 35px;
			margin: 30px 0px;
		}
		{% comment %} Display Testimonials in Equal Height Column {% endcomment %}
		.eq-row {
			display: -webkit-box;
			display: -webkit-flex;
			display: -ms-flexbox;
			display:         flex;
			flex-wrap: wrap;
		  }
		  .eq-row > [class*='col-'] {
			display: flex;
			flex-direction: column;
		  }
		{% comment %} Overriding CSS on Mobile Devices {% endcomment %}
		@media screen and (max-width: 768px) {
			.fh5co-cover .desc .desc2 {
			  display: block;
			  padding-top:0px;
			}
			.fh5co-cover{
				background-position:0px 0px !important;
			}
			.fh5co-cover .desc{
				margin-top:-150px !important;
			}
		  }
		  
		  
	</style>

	<!-- Modernizr JS -->
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="js/respond.min.js"></script>
	<![endif]-->

	</head>


{% include 'navbar.html' %}
{% include 'partials/_message.html' %}


	
	{% block content %}
	{% endblock content %}



{% include 'footer.html' %}
{% include 'scripts.html' %}

templates/footer.html
{% load static %}

<footer>
			<div id="footer">
				<div class="container">
					<div class="row row-bottom-padded-md">
						<div class="col-md-2 col-sm-2 col-xs-12 fh5co-footer-link">
							<h3>About {{this_app.app_name  }}</h3>
							<p>{{ this_app.app_description }}</p>
						</div>
						<div class="col-md-2 col-sm-2 col-xs-12 fh5co-footer-link">
							<h3>Top Activities</h3>
							<ul>
								{% for activity in top_activities %}
								<li><a href="{% url 'tour:activity-detail' activity.activity_slug %}">{{ activity.activity_title }}</a></li>
								{% endfor %}
							</ul>
						</div>
						<div class="col-md-2 col-sm-2 col-xs-12 fh5co-footer-link">
							<h3>Popular Regions</h3>
							<ul>
								{% for region in popular_regions %}
									<li><a href="{% url 'tour:region-detail' region.region_slug %}">{{ region.region_title }}</a></li>
								{% endfor %}
							</ul>
						</div>
						<div class="col-md-2 col-sm-2 col-xs-12 fh5co-footer-link">
							<h3>Best Tours</h3>
							<ul>
								{% for tour in best_tours %}
									<li><a href="{% url 'tour:tour-detail' tour.tour_slug %}">{{ tour.tour_title }}</a></li>
								{% endfor %}
							</ul>
						</div>

						{% if recent_blogs %}
						<div class="col-md-2 col-sm-2 col-xs-12 fh5co-footer-link">
							<h3>Recent Blogs</h3>
							<ul>
								{% for blog in recent_blogs %}
								<li><a href="{% url 'blog:blog-detail' blog.blog_slug %}">{{ blog.blog_title }}</a></li>
								{% endfor %}
							</ul>
						</div>
						{% endif %}

						<div class="col-md-2 col-sm-2 col-xs-12 fh5co-footer-link">
							<h3>Quick Links</h3>
							<ul>
								{% for footer_page in footer_menu %}
									<li><a href="{% url 'page:page-detail' footer_page.page_slug %}">{{ footer_page.page_title }}</a></li>
								{% endfor %}
									<li><a href="{% url 'marketing:all-testimonials' %}">Testimonials</a></li>
							</ul>

							<h3 style="margin-top:20%;">Contact Details</h3>
							<ul>
								<li><strong>Phone: </strong>{{ this_app.app_contact }}</li>
								<li><strong>Email: </strong>{{ this_app.app_email}}</li>
								<li><strong>Address: </strong>{{ this_app.app_address }}, {{ this_app.app_postal }}</li>
							</ul>
						</div>
					</div>

					{% if socialmedias %}
					<div class="row">
						<div class="col-md-6 col-md-offset-3 text-center">
							<p class="fh5co-social-icons">
								{% for socialmedia in socialmedias %}
									<a href="{{ socialmedia.socialmedia_url }}" title="{{ socialmedia.socialmedia_title }}" target="_blank"><i class="{{ socialmedia.socialmedia_icon }}"></i></a>
								{% endfor %}
							</p>
							<p>Copyright &COPY; <script>document.write(new Date().getFullYear());</script> {{ this_app.app_name }}. 
								Made with <i class="icon-heart3"></i> by 
								{% if this_app.developed_by == "Vijay Thapa" %}
								<a href="https://linktr.ee/vijaythapa" target="_blank">{{ this_app.developed_by }}</a>
								{% else %}
								{{ this_app.developed_by }}
								{% endif %}
							</p>
						</div>
					</div>
					{% endif %}

				</div>
			</div>
		</footer>

templates/head.html
{% load static %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

	{% block meta_content %}
		<title>{{ this_app.app_name }} - {{ this_app.app_title}}</title>
		<meta name="description" content="{{ this_app.app_description }}" />
		<meta name="keywords" content="{{ this_app.app_keywords }}" />


		<!-- Facebook and Twitter integration -->
		<meta property="og:title" content="{{ this_app.app_name }} - {{ this_app.app_title}}"/>
		<meta property="og:image" content="{{ this_app.app_logo.url }}"/>
		<meta property="og:url" content="{% url 'page:home' %}"/>
		<meta property="og:site_name" content="{{ this_app.app_name }} - {{ this_app.app_title}}"/>
		<meta property="og:description" content="{{ this_app.app_description }}"/>
		<meta name="twitter:title" content="{{ this_app.app_name }} - {{ this_app.app_title}}" />
		<meta name="twitter:image" content="{{ this_app.app_logo.url }}" />
		<meta name="twitter:url" content="{% url 'page:home' %}" />
		<meta name="twitter:description" content="{{ this_app.app_description }}" />
		<meta name="twitter:card" content="summary_large_image" />
	{% endblock meta_content %}


	{% block content %}

		{% if featured_tours %}

			{% for tour in featured_tours  %}
			<div class="fh5co-hero">
				<div class="fh5co-overlay"></div>
				{% if tour.tour_image %}
					<div class="fh5co-cover" data-stellar-background-ratio="0.5" style="background-image: url('{{ tour.tour_image.url }}');">
				{% else %}
					<div class="fh5co-cover" data-stellar-background-ratio="0.5" style="background-image: url({% static 'images/no-image.jpg' %});">
				{% endif %}
					<div class="desc">
						<div class="container">
							<div class="row">
								<div class="desc2 animate-box">
									<div class="col-sm-7 col-sm-push-1 col-md-7 col-md-push-1">
										<p style="color:white;">#1 Most Popular Tour Now in Nepal</p>
										<h2>{{ tour.tour_title }}</h2>
										<p>{{ tour.tour_description|safe|slice:":200" }}</p>
										<p><a class="btn btn-primary btn-lg" href="{% url 'tour:tour-detail' tour.tour_slug %}">Explore Now</a></p> 
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>

			</div>
			{% endfor %}

		{% else %}

		<div class="fh5co-hero">
			<div class="fh5co-overlay"></div>
			<div class="fh5co-cover" data-stellar-background-ratio="0.5" style="background-image: url({% static 'images/no-image.jpg' %});">
				<div class="desc">
					<div class="container">
						<div class="row">
							<div class="desc2 animate-box">
								<div class="col-sm-7 col-sm-push-1 col-md-7 col-md-push-1">
									
									<h2>Explore the Himalayas Like You've Never Seen Before</h2>
									<p>Here's the best tours that you'll love and have memory for life.</p>

									<p><a class="btn btn-primary btn-lg" href="#home_tours">Explore Tours</a></p> 
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>
		{% endif %}
		
		<!-- Regions Starts Here -->
		<span id="home_tours"></span>
		{% if regions %}
			<div id="fh5co-tours" class="fh5co-section-gray">
				<div class="container">
					<div class="row">
						<div class="col-md-8 col-md-offset-2 text-center heading-section animate-box">
							<h3>Best Regions</h3>
							<p>Best Regions to find adventure activities like Trekking, Mountain Climbing, Rafting, Canyoning and Many More.</p>
						</div>
					</div>
					<div class="row">

						{% for region in regions %}
							<div class="col-md-4 col-sm-6 fh5co-tours animate-box" data-animate-effect="fadeIn">
								<div href="#">
									{% if region.region_image %}
									<img src="{{ region.region_image.url }}" alt="{{ region.region_title }}" class="img-responsive" style="height:320px; width:100%;">
									{% else %}
									<img src="{% static 'images/no-image.jpg' %}" alt="Travel Nepal" class="img-responsive" style="height:320px; width:100%;">
									{% endif %}

									<div class="desc">
										<span></span>
										<h3>{{ region.region_title }}</h3>
										<br>
										<a class="btn btn-primary btn-outline" href="{% url 'tour:region-detail' region.region_slug %}">Explore Tours <i class="icon-arrow-right22"></i></a>
									</div>
								</div>
							</div>
						{% endfor %}

						<div class="col-md-12 text-center animate-box">
							<p><a class="btn btn-primary btn-outline btn-lg" href="{% url 'tour:all-regions' %}">See All Regions <i class="icon-arrow-right22"></i></a></p>
						</div>
					</div>
				</div>
			</div>
		{% endif %}
		<!-- Regions Ends Here -->

		<!-- Activities Starts Here -->
		{% if activities %}
			<div id="fh5co-features">
				<div class="container">
					<div class="row">

						{% for activity in activities %}
						<div class="col-md-4 animate-box">
							<div class="feature-left">
								<span class="icon">
									<a href="{% url 'tour:activity-detail' activity.activity_slug %}">
									{% if activity.activity_icon %}
										<img src="{{  activity.activity_icon }}" alt="{{ activity.activity_title }}" class="img-responsive">
									{% else %}
										<i class="icon-hotairballoon"></i>
									{% endif %}
									</a>
								</span>
								<div class="feature-copy">
									<h3>{{ activity.activity_title }}</h3>
									<p>{{ activity.activity_description|safe|slice:":70" }} ...</p>
									<p><a href="{% url 'tour:activity-detail' activity.activity_slug %}">Learn More</a></p>
								</div>
							</div>
						</div>
						{% endfor %}

					</div>
				</div>
			</div>
		{% endif %}
		<!-- Activities Ends Here -->

		
		<!-- Tours Starts Here -->
		{% if tours %}
			<div id="fh5co-destination">
				<div class="tour-fluid">
					<div class="row">
						<div class="col-md-12">
							<ul id="fh5co-destination-list" class="animate-box">

								{% for tour in tours %}

									{% if forloop.counter == 6 %}
										<li class="one-half text-center">
											<div class="title-bg">
												<div class="case-studies-summary">
													<h2>Most Popular Destinations</h2>
													<span><a href="{% url 'tour:all-tours' %}">View All Destinations</a></span>
												</div>
											</div>
										</li>
									{% endif %}

									{% if tour.tour_image %}
										<li class="one-forth text-center" style="background-image: url({{ tour.tour_image.url  }}); ">
									{% else %}
										<li class="one-forth text-center" style="background-image: url({% static 'images/no-image.jpg' %}); ">
									{% endif %}
									
										<a href="{% url 'tour:tour-detail' tour.tour_slug %}">
											<div class="case-studies-summary">
												<h2>{{ tour.tour_title }}</h2>
											</div>
										</a>
									</li>
									
								{% endfor %}

								
							</ul>		
						</div>
					</div>
				</div>
			</div>
		{% endif %}
		<!-- Tours Ends Here -->


		<!-- Blogs Starts Here -->
		{% if blogs %}
		<div id="fh5co-blog-section" class="fh5co-section-gray">
			<div class="container">
				<div class="row">
					<div class="col-md-8 col-md-offset-2 text-center heading-section animate-box">
						<h3>Recent From Blog</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit est facilis maiores, perspiciatis accusamus asperiores sint consequuntur debitis.</p>
					</div>
				</div>
			</div>
			<div class="container">
				<div class="row row-bottom-padded-md">

					{% for blog in blogs %}
					<div class="col-lg-4 col-md-4 col-sm-6">
						<div class="fh5co-blog animate-box">

							{% if blog.blog_image %}
								<a href="{% url 'blog:blog-detail' blog.blog_slug %}"><img class="img-responsive" src="{{ blog.blog_image.url }}" alt="{{ blog.blog_title }}" style="height:200px; width:100%;"></a>
							{% else %}
								<a href="{% url 'blog:blog-detail' blog.blog_slug %}"><img class="img-responsive" src="{% static 'images/no-image.jpg' %}" alt="{{ blog.blog_title }}" style="height:200px; width:100%;"></a>
							{% endif %}

							<div class="blog-text">
								<div class="prod-title">
									<h3><a href="{% url 'blog:blog-detail' blog.blog_slug %}">{{ blog.blog_title }}</a></h3>
									<span class="posted_by">{{ blog.blog_created_at }}</span>
									{% comment %} <span class="comment"><a href="">21<i class="icon-bubble2"></i></a></span> {% endcomment %}
									<div>{{ blog.blog_description|safe|slice:":100" }} ...</div>
									<p><a href="{% url 'blog:blog-detail' blog.blog_slug %}">Read More...</a></p>
								</div>
							</div> 
						</div>
					</div>
					{% endfor %}
					<div class="clearfix visible-md-block"></div>
				</div>

				<div class="col-md-12 text-center animate-box">
					<p><a class="btn btn-primary btn-outline btn-lg" href="{% url 'blog:all-blogs' %}">See All Blogs <i class="icon-arrow-right22"></i></a></p>
				</div>

			</div>
		</div>
		{% endif %}
		<!-- Blog Ends Here -->

		<div class="subscribe">
			<div class="container">
				<h2 class="text-center">Subscribe To Our Newsletter</h2>
				<form method="POST" action=".">
					{% csrf_token %}
				  <div class="row">
				    <div class="col-md-9">
				      <input type="email" name="subscriber_email" class="form-control form-control-lg" placeholder="Your Email" required="True">
				    </div>
				    <div class="col-md-3">
				      <button class="form-control btn btn-primary btn-lg">SUBSCRIBE</button>
				    </div>
				  </div>
				</form>
			</div>
		</div>


		<!-- fh5co-testimonials-section -->
		 {% if testimonials %}
		<div id="fh5co-testimonial">
		<div class="container">
			<div class="row animate-box">
				<div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
					<h2>Happy Clients</h2>
				</div>
			</div>
			<div class="row">

				{% for testimonial in testimonials %}
				<div class="col-md-4">
					<div class="box-testimony animate-box">
						<blockquote>
							<span class="quote"><span><i class="icon-quotes-right"></i></span></span>
							<p>&ldquo;{{ testimonial.testimonial }}&rdquo;</p>
						</blockquote>
						<p class="author">{{ testimonial.customer_name }}, <span style="color: #98D7BE;">{{ testimonial.customer_company}}</span> <span class="subtext">{{ testimonial.customer_job_title }}</span></p>
					</div>
					
				</div>
				{% endfor %}
			</div>

			<div class="col-md-12 text-center animate-box">
				<p><a class="btn btn-success btn-outline-success btn-lg" href="{% url 'marketing:all-testimonials' %}">See All Testimonials <i class="icon-arrow-right22"></i></a></p>
			</div>

		</div>
	</div>
	{% endif %}
	
	{% endblock content %}

templates/navbar.html
{% load static %}

	<body>
		<div id="fh5co-wrapper">
		<div id="fh5co-page">

		<header id="fh5co-header-section" class="sticky-banner">
			<div class="container">
				<div class="nav-header">
					<a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle dark"><i></i></a>
					{% if this_app.app_logo %}
					<a href="{% url 'page:home' %}"><img src="{{ this_app.app_logo.url }}" alt="{{ this_app.app_name }}" class="img-logo"></a>
					{% else %}
					<h1 id="fh5co-logo"><a href="{% url 'page:home' %}"><i class="icon-airplane"></i>{{ this_app.app_name }}</a></h1>
					{% endif %}
					<!-- START #fh5co-menu-wrap -->
					<nav id="fh5co-menu-wrap" role="navigation">
						<ul class="sf-menu" id="fh5co-primary-menu">
							<li class="{% if request.resolver_match.url_name == 'home' %}active{% endif %}"><a href="{% url 'page:home' %}">Home</a></li>
							{% for top_page in top_menu %}
								<li class="{% if top_page.page_slug in request.path %}active{% endif %}"><a href="{% url 'page:page-detail' top_page.page_slug %}">{{ top_page.page_title }}</a></li>
							{% endfor %}

							<li class="{% if 'activit' in request.path %}active{% endif %}">
								<a href="{% url 'tour:all-activities' %}" class="fh5co-sub-ddown">Activities</a>
								<ul class="fh5co-sub-menu">
									{% for activity in activity_menu %}
										<li><a href="{% url 'tour:activity-detail' activity.activity_slug %}">{{ activity.activity_title }}</a></li>
									{% endfor %}
								</ul>
							</li>
							<li class="{% if 'region' in request.path %}active{% endif %}">
								<a href="{% url 'tour:all-regions' %}" class="fh5co-sub-ddown">Regions</a>
								<ul class="fh5co-sub-menu">
									{% for region in region_menu %}
										<li><a href="{% url 'tour:region-detail' region.region_slug %}">{{ region.region_title }}</a></li>
									{% endfor %}
								</ul>
							</li>
							<li class="{% if 'blog' in request.path %}active{% endif %}"><a href="{% url 'blog:all-blogs' %}">Blogs</a></li>
							<li class="{% if 'contact' in request.path %}active{% endif %}"><a href="{% url 'page:contact' %}">Contact</a></li>
						</ul>
					</nav>
				</div>
			</div>
		</header>

		<!-- end:header-top -->

templates/scripts.html
{% load static %}
	

	</div>
	<!-- END fh5co-page -->

	</div>
	<!-- END fh5co-wrapper -->

	<!-- jQuery -->


	<script src="{% static 'js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
	<script src="{% static 'js/sticky.js' %}"></script>

	<!-- Stellar -->
	<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
	<!-- Superfish -->
	<script src="{% static 'js/hoverIntent.js' %}"></script>
	<script src="{% static 'js/superfish.js' %}"></script>
	<!-- Magnific Popup -->
	<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'js/magnific-popup-options.js' %}"></script>
	<!-- Date Picker -->
	<script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
	<!-- CS Select -->
	<script src="{% static 'js/classie.js' %}"></script>
	<script src="{% static 'js/selectFx.js' %}"></script>
	
	<!-- Main JS -->
	<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>